### ISSUE TITLE
Não há NAV.

### ISSUE THREAD

**Issue by ambs309** [afonso-saaa/afonso-saaa.github.io#2]
https://github.com/afonso-saaa/afonso-saaa.github.io/blob/ddc2afafe7f63c171fd28fc49c7f33e767472eda/lab4/viagem.html#L10

Não é bem nesta linha, usei-a só como referencia para inserir um issue.
No geral tens tudo correto, gostei bastante, tens é um problema relativamente simples de resolver, mas que afeta bastante o quão boas são as tuas secções quiz e viagem...
E o que é perguntas tu?
Bem o título é bastante auto-explicativo, não tens NAV no Quiz nem na viagem, então caso queiramos ir para outras páginas não conseguimos.
Mas é só isso.

**Comment by afonso-saaa** [comment]
Obrigado! Já  está corrigido
